#!/usr/bin/env bash

# todo. add yaml front matter include "code: true"

Top=$(git rev-parse --show-toplevel)

There=$Top/../code/src

worker() {
gawk 'BEGIN {  
         q="\""
         print ""
         First = 1      
         In = 1
  }         
  /^# /{ sub(/^#/,"")
        print "---"
        print "title: " $0
        print "layout: default"
        print "hascode: true"
        print "---"
        print ""
      }
  /^"""</,/^>"""/ {  next } 
  /^"""/          {  In = 1 - In       
                     if (In)            
                       print "````python"
                     else          
                       if (First)   
                         First = 0   
                       else     
                         print "````"  
                     next }       
  ! First { print (In ? sprintf("%4s. ",++n) : "") $0 }       
  END     { if (In) print "````"
            }'
} 
main() {
  arg=$1
  file=$(basename $arg)
  stem="${file%%.*}"
  out=$Top/${stem}.md
  echo "# $(basename $arg) ==> $out"
  cat $1 | worker  > $out
  git add $out
}
if [ -n "$1" ]; then
  main $1
  git commit -am as
else
  for f in $There/*.md; do
    main $f
  done
  for f in $There/*.put; do
    main $f
   done
  git commit -am as
  git push
fi

